name: 🛠️ Melhoria
description: Sugira uma melhoria para algo já existente
title: "[Enhancement] "
labels: [enhancement]
body:
  - type: textarea
    id: contexto
    attributes:
      label: Contexto
      description: O que pode ser melhorado e por quê?
    validations:
      required: true

  - type: textarea
    id: proposta
    attributes:
      label: Proposta de melhoria
      description: Como você sugere melhorar essa parte do sistema?
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: Impacto esperado
      description: Como isso melhora a experiência do usuário ou do time?
    validations:
      required: false
