name: 🚀 Nova Feature
description: Sugira uma nova funcionalidade
title: "[Feature] "
labels: [feature]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva a funcionalidade desejada e sua utilidade.
      placeholder: Exemplo: Quero adicionar login com redes sociais para facilitar o acesso.
    validations:
      required: true

  - type: textarea
    id: justificativa
    attributes:
      label: Justificativa
      description: Por que essa feature é importante? Como ela melhora o projeto?
    validations:
      required: false

  - type: textarea
    id: detalhes
    attributes:
      label: Detalhes adicionais
      description: Alguma sugestão técnica, mockup ou referência?
    validations:
      required: false
