name: 📋 Task
description: Crie uma tarefa geral que não se enquadra em bug ou feature
title: "[Task] "
labels: [task]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição da tarefa
      description: Explique o que precisa ser feito.
    validations:
      required: true

  - type: textarea
    id: criterios
    attributes:
      label: Critérios de aceitação
      description: O que define que a tarefa foi concluída com sucesso?
    validations:
      required: false
